name: 'Mirror a repository using SSH'
description: 'Action for mirroring a repository in another location (Bitbucket, GitHub, GitLab, …) using SSH.'
branding:
  icon: 'copy'
  color: 'orange'
inputs:
  source-repo:
    description: 'SSH URL of the source repo.'
    required: true
  destination-repo:
    description: 'SSH URL of the destination repo.'
    required: true
  branches:
    description: ', seperated, branches to mirror'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-repo }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.branches }}
    